/*
 * generated by Xtext
 */
package kilic.demo.lambda;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LambdaRuntimeModule extends kilic.demo.lambda.AbstractLambdaRuntimeModule {

}
