/*
 * generated by Xtext
 */
package kilic.demo.arconf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ARConfUiModule extends kilic.demo.arconf.ui.AbstractARConfUiModule {
	public ARConfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
