/*
 * generated by Xtext
 */
package kilic.demo.lambda.ui.contentassist

import kilic.demo.lambda.ui.contentassist.AbstractLambdaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LambdaProposalProvider extends AbstractLambdaProposalProvider {
}
