/*
 * generated by Xtext
 */
package kilic.demo.arconf.ui.contentassist

import kilic.demo.arconf.ui.contentassist.AbstractARConfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ARConfProposalProvider extends AbstractARConfProposalProvider {
}
