/*
* generated by Xtext
*/
package kilic.demo.arconf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ARConfStandaloneSetup extends ARConfStandaloneSetupGenerated{

	public static void doSetup() {
		new ARConfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

