/*
 * generated by Xtext
 */
package kilic.demo.arconf;

import kilic.demo.arconf.semantics.ARConfStringRep;
import it.xsemantics.runtime.StringRepresentation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ARConfRuntimeModule extends kilic.demo.arconf.AbstractARConfRuntimeModule {
	public Class<? extends StringRepresentation> bindStringProvider() {
		return ARConfStringRep.class;
	}
}
