/*
 * generated by Xtext
 */
package kilic.demo.arconf.validation

import kilic.demo.arconf.semantics.validation.ARConfSemanticsValidator

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ARConfValidator extends ARConfSemanticsValidator {
}
