/*
 * generated by Xtext
 */
package kilic.demo.lambda.validation

import kilic.demo.lambda.lambda.LambdaPackage
import kilic.demo.lambda.lambda.Parameter
import kilic.demo.lambda.typing.validation.LambdaTypeSystemValidator
import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class LambdaValidator extends LambdaTypeSystemValidator {
	@Check
	def void checkParam(Parameter p) {
		if(p.paramType==null) {
			warning('param type is null',p, LambdaPackage.Literals.PARAMETER__PARAM_TYPE)
		}
	}
}
