/*
 * generated by Xtext
 */
package kilic.demo.lambda.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LambdaUiModule extends kilic.demo.lambda.ui.AbstractLambdaUiModule {
	public LambdaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
